routes/news.py
from flask import Blueprint, render_template, abort, request, flash, redirect, url_for

from redis_cache import NewsCache
from models.models import News, Comments
from forms.forms import CommentForm

from utils.utils import require_appkey

news_api = Blueprint("news_api", __name__)


@news_api.route("/", methods=["GET"])
def index():
    # load from redis
    cache_obj = NewsCache()
    news_list = cache_obj.get_index_news()
    # search from mysql
    # news_list = News.query.filter(
    #     News.is_valid == True,
    #     News.is_top == True,
    # ).all()
    return render_template(
        "index.html",
        news_list=news_list,
    )


@news_api.route("/cat/<news_type>", methods=["GET"])
def cat(news_type):
    news_list = News.query.filter(
        News.is_valid == True,
        News.news_type == news_type,
    ).all()
    return render_template(
        "cat.html",
        news_list=news_list,
    )


@news_api.route("/detail/<int:pk>", methods=["GET"])
def detail(pk):
    news_obj = News.query.get(pk)
    form = CommentForm(
        data={
            "object_id": pk,
        }
    )

    if not news_obj or not news_obj.is_valid:
        abort(404)
    return render_template(
        "detail.html",
        news_obj=news_obj,
        form=form,
    )


@news_api.route("/comment/<int:news_id>/add", methods=["POST"])
def comment_add(news_id):
    form = CommentForm(
        data={
            "object_id": news_id,
        }
    )
    news_obj = News.query.get(news_id)
    # submit
    if request.method == "POST":
        if form.validate_on_submit():
            comment_obj = Comments(
                content=form.content.data,
                object_id=news_id,
            )
            print("add comment now: ", comment_obj)
            reply_id = form.reply_id.data
            if reply_id:
                comment_obj.reply_id = reply_id
            comment_obj.save()
            print("added comments")
            flash("comment has been added!", "success")
            return redirect(url_for("news_api.detail", pk=news_id))
        else:
            print("error: ", form.errors)
            flash("invalid input", "danger")

    return render_template(
        "detail.html",
        form=form,
        news_obj=news_obj,
    )

templates/cat.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <link rel="stylesheet" href="/static/css/index.css" />
    <title>Flask</title>
  </head>

  <body>
    <header>
      <nav>
        <ul>
          <li><a href="/">Home</a></li>
          <li><a href="/cat/local">Local</a></li>
          <li><a href="/cat/global">Global</a></li>
          <li><a href="/cat/entertainment">Entertaiment</a></li>
          <li><a href="/cat/miltary">Miltary</a></li>
        </ul>
      </nav>
    </header>
    <article>
      {% for item in news_list %}
      <div class="list-news">
        <div class="img-content">
          <img src="{{ item.img_url }}" alt="image" />
        </div>
        <div class="right-content">
          <p><a href="/detail/{{ item.id }}">{{ item.title }}</a></p>
          <small>{{ item.created_at }}</small>
        </div>
      </div>
      {% endfor %}
    </article>
  </body>
</html>

templates/detail.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <title>Flask</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/static/css/index.css" />
  </head>

  <body>
    <header>
      <nav>
        <ul>
          <li><a href="/">Home</a></li>
          <li><a href="/cat/local">Local</a></li>
          <li><a href="/cat/global">Global</a></li>
          <li><a href="/cat/entertainment">Entertaiment</a></li>
          <li><a href="/cat/miltary">Miltary</a></li>
        </ul>
      </nav>
    </header>
    <article>
      <div class="container">
        <!--  -->
        {% for category, message in get_flashed_messages(with_categories=True)
        %}
        <div class="alert alert-{{ category }}">
          <button type="button" class="close" data-dismiss="alert">×</button>
          {{ message }}
        </div>
        {% endfor %}
        <!--  -->
        <h3>{{ news_obj.title }}</h3>
        <p>
          Category: <b>{{ news_obj.news_type }}</b>
          <small class="pull-right text-muted"
            >Published: {{ news_obj.created_at }}</small
          >
        </p>
        <hr />
        <img src="{{ news_obj.img_url }}" alt="image" />
        <p>{{ news_obj.content }}</p>
        <hr />
        <h4>Comments</h4>
        {% for comment_obj in news_obj.get_comments() %}
        <blockquote>
          {{comment_obj.content}}
          <footer class="text-muted text-right">
            {{comment_obj.created_at}}
          </footer>
        </blockquote>
        {% endfor %}
        <hr />
        <h4>Comment</h4>
        <form
          class="comment-form"
          method="post"
          action="{{url_for('news_api.comment_add', news_id=news_obj.id)}}"
        >
          <div class="form-group">
            {{form.content}}
            <!--  -->
            {% if form.content.errors %}
            <span class="text-danger"> {{ form.content.errors[0] }} </span>
            {% endif %}
            <!-- <textarea
              class="form-control"
              id="content"
              name="content"
              required="required"
            ></textarea> -->
          </div>
          <div class="form-group text-right">
            {{ form.csrf_token }}
            <!--  -->
            {{ form.object_id }}
            <!--  -->
            {{ form.reply_id }}
            <!--  -->
            {{ form.submit }}
          </div>
        </form>
      </div>
    </article>
    <script src="/static/jquery.1.10.2.min.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
  </body>
</html>

templates/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <link rel="stylesheet" href="/static/css/index.css" />
    <title>Flask</title>
  </head>

  <body>
    <header>
      <nav>
        <ul>
          <li><a href="/">Home</a></li>
          <li><a href="/cat/local">Local</a></li>
          <li><a href="/cat/global">Global</a></li>
          <li><a href="/cat/entertainment">Entertaiment</a></li>
          <li><a href="/cat/miltary">Miltary</a></li>
        </ul>
      </nav>
    </header>
    <article>
      {% for item in news_list %}
      <div class="list-news">
        <div class="img-content">
          <img src="{{ item.img_url }}" alt="image" />
        </div>
        <div class="right-content">
          <p><a href="/detail/{{ item.id }}">{{ item.title }}</a></p>
          <small>{{ item.created_at }}</small>
        </div>
      </div>
      {% endfor %}
    </article>
  </body>
</html>